version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: 'dockerfiles/nginx.dockerfile'
    ports:
      - '8000:80'

    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './src:/var/www/html'
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: 'dockerfiles/php.dockerfile'
    volumes:
      - './src:/var/www/html:delegated'
    ports:
      - '3000:9000'

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - 'my-sql-volume:/var/lib/mysql'

  composer:
    build:
      context: './dockerfiles'
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: '.'
      dockerfile: 'dockerfiles/php.dockerfile'
    volumes:
      - ./src:/var/www/html

    entrypoint: ['php', '/var/www/html/artisan']

  npm:
    image: node:14

    working_dir: /var/www/html

    stdin_open: true
    tty: true

    entrypoint: ['npm']

volumes:
  my-sql-volume: